= Codename One CSS Project Bootstrap

A bootstrap basic hello world https://www.codenameone.com/[Codename One] project with the CSS plugin installed.

== Installation

Installation requires the https://github.com/shannah/codenameone-cli[Codename One CLI] to be installed.

[source,bash]
----
$ cn1 create <destdir> <package> <main-class-name> \n
    -i [Netbeans|Eclipse|IntelliJ] \n
    -t https://github.com/shannah/cn1-css-bootstrap/archive/master.zip
----

Where `<destdir>` is the path to the project directory that should be created for your project, `<package>` is the java package for your project, and
`<main-class-name>` is the main class name.

Example.  To create a Codename One Netbeans project that has CSS setup with main class name com.example.myapp.MyCSSApp, in the directory myapp you would do:
[source,bash]
----
$ cn1 create myapp com.example.myapp MyCSSApp -i Netbeans -t https://github.com/shannah/cn1-css-bootstrap/archive/master.zip
----

Alternatively you can run graphical wizard using:

[source,bash]
----
$ cn1 create -g myapp
----

And paste the template url "https://github.com/shannah/cn1-css-bootstrap/archive/master.zip" in the template field.

IMPORTANT: The first time you open the project, you may may need to update the project libs.  In Netbeans you would do this by opening the project properties, then press the "Update Project Libs" button.  In Eclipse and IntelliJ is is similar.
